name: Build filter-id
 
on:
  push:
    branches: [ main ]

  schedule:
    - cron: '0 22 * * *'

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Download repository
      uses: actions/checkout@v2

    - name: Download dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        
    - name: Running build/generation script
      shell: bash
      run: |
        bash ./generate.sh 2>&1
        
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%F %H:%M:%S')"

    - name: Generate tag name
      run: echo "TAG_NAME=$(date +%F_%H-%M-%S)" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.dat
        name: Build ${{ steps.date.outputs.date }}
        tag_name: ${{ env.TAG_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete older releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 1
        delete_tags: true 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
